import os

import dotenv
from telethon import TelegramClient

dotenv.load_dotenv()


account_1 = TelegramClient('account_1', os.getenv("ACCOUNT_1_API_ID"), os.getenv("ACCOUNT_1_API_HASH"))
account_2 = TelegramClient('account_2', os.getenv("ACCOUNT_2_API_ID"), os.getenv("ACCOUNT_2_API_HASH"))
account_3 = TelegramClient('account_3', os.getenv("ACCOUNT_3_API_ID"), os.getenv("ACCOUNT_3_API_HASH"))
account_4 = TelegramClient('account_4', os.getenv("ACCOUNT_4_API_ID"), os.getenv("ACCOUNT_4_API_HASH"))
account_5 = TelegramClient('account_5', os.getenv("ACCOUNT_5_API_ID"), os.getenv("ACCOUNT_5_API_HASH"))
account_6 = TelegramClient('account_6', os.getenv("ACCOUNT_6_API_ID"), os.getenv("ACCOUNT_6_API_HASH"))
account_7 = TelegramClient('account_7', os.getenv("ACCOUNT_7_API_ID"), os.getenv("ACCOUNT_7_API_HASH"))
account_8 = TelegramClient('account_8', os.getenv("ACCOUNT_8_API_ID"), os.getenv("ACCOUNT_8_API_HASH"))
account_9 = TelegramClient('account_9', os.getenv("ACCOUNT_9_API_ID"), os.getenv("ACCOUNT_9_API_HASH"))
account_10 = TelegramClient('account_10', os.getenv("ACCOUNT_10_API_ID"), os.getenv("ACCOUNT_10_API_HASH"))
account_11 = TelegramClient('account_11', os.getenv("ACCOUNT_11_API_ID"), os.getenv("ACCOUNT_11_API_HASH"))
account_12 = TelegramClient('account_12', os.getenv("ACCOUNT_12_API_ID"), os.getenv("ACCOUNT_12_API_HASH"))
account_13 = TelegramClient('account_13', os.getenv("ACCOUNT_13_API_ID"), os.getenv("ACCOUNT_13_API_HASH"))
account_14 = TelegramClient('account_14', os.getenv("ACCOUNT_14_API_ID"), os.getenv("ACCOUNT_14_API_HASH"))
account_15 = TelegramClient('account_15', os.getenv("ACCOUNT_15_API_ID"), os.getenv("ACCOUNT_15_API_HASH"))
account_16 = TelegramClient('account_16', os.getenv("ACCOUNT_16_API_ID"), os.getenv("ACCOUNT_16_API_HASH"))
account_17 = TelegramClient('account_17', os.getenv("ACCOUNT_17_API_ID"), os.getenv("ACCOUNT_17_API_HASH"))
account_18 = TelegramClient('account_18', os.getenv("ACCOUNT_18_API_ID"), os.getenv("ACCOUNT_18_API_HASH"))
account_19 = TelegramClient('account_19', os.getenv("ACCOUNT_19_API_ID"), os.getenv("ACCOUNT_19_API_HASH"))
account_20 = TelegramClient('account_20', os.getenv("ACCOUNT_20_API_ID"), os.getenv("ACCOUNT_20_API_HASH"))
account_21 = TelegramClient('account_21', os.getenv("ACCOUNT_21_API_ID"), os.getenv("ACCOUNT_21_API_HASH"))
account_22 = TelegramClient('account_22', os.getenv("ACCOUNT_22_API_ID"), os.getenv("ACCOUNT_22_API_HASH"))
account_23 = TelegramClient('account_23', os.getenv("ACCOUNT_23_API_ID"), os.getenv("ACCOUNT_23_API_HASH"))
account_24 = TelegramClient('account_24', os.getenv("ACCOUNT_24_API_ID"), os.getenv("ACCOUNT_24_API_HASH"))
account_25 = TelegramClient('account_25', os.getenv("ACCOUNT_25_API_ID"), os.getenv("ACCOUNT_25_API_HASH"))
account_26 = TelegramClient('account_26', os.getenv("ACCOUNT_26_API_ID"), os.getenv("ACCOUNT_26_API_HASH"))
account_27 = TelegramClient('account_27', os.getenv("ACCOUNT_27_API_ID"), os.getenv("ACCOUNT_27_API_HASH"))
account_28 = TelegramClient('account_28', os.getenv("ACCOUNT_28_API_ID"), os.getenv("ACCOUNT_28_API_HASH"))
account_29 = TelegramClient('account_29', os.getenv("ACCOUNT_29_API_ID"), os.getenv("ACCOUNT_29_API_HASH"))
account_30 = TelegramClient('account_30', os.getenv("ACCOUNT_30_API_ID"), os.getenv("ACCOUNT_30_API_HASH"))
account_31 = TelegramClient('account_31', os.getenv("ACCOUNT_31_API_ID"), os.getenv("ACCOUNT_31_API_HASH"))
account_32 = TelegramClient('account_32', os.getenv("ACCOUNT_32_API_ID"), os.getenv("ACCOUNT_32_API_HASH"))
account_33 = TelegramClient('account_33', os.getenv("ACCOUNT_33_API_ID"), os.getenv("ACCOUNT_33_API_HASH"))
account_34 = TelegramClient('account_34', os.getenv("ACCOUNT_34_API_ID"), os.getenv("ACCOUNT_34_API_HASH"))
account_35 = TelegramClient('account_35', os.getenv("ACCOUNT_35_API_ID"), os.getenv("ACCOUNT_35_API_HASH"))
account_36 = TelegramClient('account_36', os.getenv("ACCOUNT_36_API_ID"), os.getenv("ACCOUNT_36_API_HASH"))
account_37 = TelegramClient('account_37', os.getenv("ACCOUNT_37_API_ID"), os.getenv("ACCOUNT_37_API_HASH"))
account_38 = TelegramClient('account_38', os.getenv("ACCOUNT_38_API_ID"), os.getenv("ACCOUNT_38_API_HASH"))
account_39 = TelegramClient('account_39', os.getenv("ACCOUNT_39_API_ID"), os.getenv("ACCOUNT_39_API_HASH"))
account_40 = TelegramClient('account_40', os.getenv("ACCOUNT_40_API_ID"), os.getenv("ACCOUNT_40_API_HASH"))
account_41 = TelegramClient('account_41', os.getenv("ACCOUNT_41_API_ID"), os.getenv("ACCOUNT_41_API_HASH"))
account_42 = TelegramClient('account_42', os.getenv("ACCOUNT_42_API_ID"), os.getenv("ACCOUNT_42_API_HASH"))
account_43 = TelegramClient('account_43', os.getenv("ACCOUNT_43_API_ID"), os.getenv("ACCOUNT_43_API_HASH"))
account_44 = TelegramClient('account_44', os.getenv("ACCOUNT_44_API_ID"), os.getenv("ACCOUNT_44_API_HASH"))
account_45 = TelegramClient('account_45', os.getenv("ACCOUNT_45_API_ID"), os.getenv("ACCOUNT_45_API_HASH"))
