from config import *


# Запуск всех аккаунтов
print("Запуск account_1")
account_1.start()
print("Запуск account_2")
account_2.start()
print("Запуск account_3")
account_3.start()
print("Запуск account_4")
account_4.start()
print("Запуск account_5")
account_5.start()
print("Запуск account_6")
account_6.start()
print("Запуск account_7")
account_7.start()
print("Запуск account_8")
account_8.start()
print("Запуск account_9")
account_9.start()
print("Запуск account_10")
account_10.start()
print("Запуск account_11")
account_11.start()
print("Запуск account_12")
account_12.start()
print("Запуск account_13")
account_13.start()
print("Запуск account_14")
account_14.start()
print("Запуск account_15")
account_15.start()
print("Запуск account_16")
account_16.start()
print("Запуск account_17")
account_17.start()
print("Запуск account_18")
account_18.start()
print("Запуск account_19")
account_19.start()
print("Запуск account_20")
account_20.start()
print("Запуск account_21")
account_21.start()
print("Запуск account_22")
account_22.start()
print("Запуск account_23")
account_23.start()
print("Запуск account_24")
account_24.start()
print("Запуск account_25")
account_25.start()
print("Запуск account_26")
account_26.start()
print("Запуск account_27")
account_27.start()
print("Запуск account_28")
account_28.start()
print("Запуск account_29")
account_29.start()
print("Запуск account_30")
account_30.start()
print("Запуск account_31")
account_31.start()
print("Запуск account_32")
account_32.start()
print("Запуск account_33")
account_33.start()
print("Запуск account_34")
account_34.start()
print("Запуск account_35")
account_35.start()
print("Запуск account_36")
account_36.start()
print("Запуск account_37")
account_37.start()
print("Запуск account_38")
account_38.start()
print("Запуск account_39")
account_39.start()
print("Запуск account_40")
account_40.start()
print("Запуск account_41")
account_41.start()
print("Запуск account_42")
account_42.start()
print("Запуск account_43")
account_43.start()
print("Запуск account_44")
account_44.start()
print("Запуск account_45")
account_45.start()

print("Done! All accounts were connected")



# TODO:
#  0) Спросить Владимира .env файл с API_HASH и API_ID аккаунтов ТГ
#  0.5) Настроить и подключить свой сервисный аккаунт Гугл для доступа к таблице по API
#  1) Сделать функцию определения нужно аккаунта исходя из номера телефона в таблице (чтобы сообщение уходило с нужного аккаунта) - ХАРДКОД
#  2) Используя готовые функции, которые уже я написал реализовать отправку сообщений с МЕДИА ОБЯЗАТЕЛЬНО - внимательно надо читать документацию
#  3) Выбрать либо cron либо просто по проверке времени циклом реализовать логику: Если время 5 утра (МСК), то начинаем отправлять сообщения,
#  прям по очереди каждую строку таблицы обрабатывая
#  (определяем аккаунт номером ->
#  скачиваем фото все - отправляем в каждую из групп ПО ОЧЕРЕДИ чтобы не забанить аккаунт ->
#  удаляем фотки и ПЕРЕХОДИМ К СЛЕДУЮЩЕЙ СТРОКЕ)
#  4) Тестим и ставим на докер желательно



