from config import *

# data = get_data()
# account_1.start()
account_2.start()
account_3.start()
account_4.start()
account_5.start()
account_6.start()
account_7.start()
account_8.start()
account_9.start()
account_10.start()
account_11.start()
account_12.start()
account_13.start()
account_14.start()
account_15.start()
account_16.start()
account_17.start()
account_18.start()
account_19.start()
account_20.start()
account_21.start()
account_22.start()
account_23.start()
account_24.start()
account_25.start()
account_26.start()
account_27.start()
account_28.start()
account_29.start()
account_30.start()
account_31.start()
account_32.start()
account_33.start()
account_34.start()
account_35.start()
account_36.start()
account_37.start()
account_38.start()
account_39.start()
account_40.start()
account_41.start()
account_42.start()
account_43.start()
account_44.start()
# account_45.start()

print(done)

